services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - simsim

  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - simsim

networks:
  simsim:
    driver: bridge

volumes:
  redis_data: