services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - simsim

  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--bind", "0.0.0.0"]
    ports:
      - "6379:6379"
    networks:
      - simsim

networks:
  simsim:
    driver: bridge

volumes:
  redis_data: