name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APP }}" > src/main/resources/application.yml
          echo "${{ secrets.PROP }}" > src/main/resources/application.properties
          mkdir -p gradle/wrapper
          echo "${{ secrets.GRADLE_WRAPPER }}" > gradle/wrapper/gradle-wrapper.properties

      - name: Transfer files to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          TARGET_HOST: ${{ secrets.TARGET_HOST }}
          TARGET_USER: ${{ secrets.TARGET_USER }}
          TARGET_PATH: ${{ secrets.TARGET_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $TARGET_HOST >> ~/.ssh/known_hosts

          # 코드 파일을 서버로 전송
          rsync -avz --exclude='.git' . $TARGET_USER@$TARGET_HOST:$TARGET_PATH

      - name: Build and deploy on server
        env:
          TARGET_USER: ${{ secrets.TARGET_USER }}
          TARGET_HOST: ${{ secrets.TARGET_HOST }}
          TARGET_PATH: ${{ secrets.TARGET_PATH }}
        run: |
          ssh $TARGET_USER@$TARGET_HOST << EOF
            cd $TARGET_PATH
            make all
          EOF